<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="Xunit.SkippableFact" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AspireHcs\AspireHcs.csproj" />
    <Compile Remove="FakeHcsCtl.cs" />
  </ItemGroup>

  <Target Name="PublishFakeHcsCtl" AfterTargets="Build">
    <Exec Command='dotnet publish "$(MSBuildProjectDirectory)\FakeHcsCtl.cs" --configuration "$(Configuration)" --output "$(OutDir)fake-hcsctl"' />
  </Target>

</Project>
